input.onButtonPressed(Button.A, function () {
    for (let index = 0; index < 15; index++) {
        strip.showColor(neopixel.rgb(255, 0, 0))
        strip.showColor(neopixel.rgb(0, 0, 255))
    }
})
input.onButtonPressed(Button.B, function () {
    for (let index = 0; index < 15; index++) {
        strip.showColor(neopixel.rgb(255, 0, 0))
        strip.showColor(neopixel.rgb(0, 255, 255))
    }
})
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
basic.showString("Kiketon Rivera")
basic.showLeds(`
    # . . . #
    . # . # .
    . . . . .
    # # # # #
    # . # . #
    `)
basic.forever(function () {
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(25, 72, 135))
    music.rest(music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(255, 45, 180))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(76, 89, 245))
    music.playTone(262, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.rgb(97, 234, 90))
    music.playTone(262, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.rgb(62, 34, 0))
    music.playTone(262, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.rgb(78, 34, 90))
    music.playTone(262, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.rgb(28, 57, 177))
    music.rest(music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(7, 7, 7))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(200, 180, 160))
    music.rest(music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(7, 69, 96))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(65, 100, 69))
    music.playTone(262, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.rgb(85, 92, 132))
    music.playTone(262, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.rgb(7, 4, 0))
    music.playTone(262, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.rgb(26, 193, 52))
    music.playTone(262, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.rgb(95, 38, 75))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(11, 232, 255))
    music.rest(music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(27, 95, 204))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.rgb(45, 23, 87))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(69, 123, 36))
    music.rest(music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(55, 168, 199))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(255, 255, 255))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(255, 255, 255))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(38, 62, 92))
    music.rest(music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(37, 13, 198))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(15, 20, 40))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(184, 91, 67))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(139, 200, 72))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(56, 39, 90))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.rgb(45, 65, 32))
})
