input.onButtonPressed(Button.A, function () {
    for (let index = 0; index < 15; index++) {
        music.playTone(880, music.beat(BeatFraction.Whole))
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        music.playTone(523, music.beat(BeatFraction.Whole))
        strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    }
})
input.onButtonPressed(Button.B, function () {
    for (let index = 0; index < 15; index++) {
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    }
})
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
basic.showString("Kiketon Rivera")
basic.showLeds(`
    # . . . #
    . # . # .
    . . . . .
    # # # # #
    # . # . #
    `)
basic.forever(function () {
    music.playTone(698, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.rest(music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(698, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.rest(music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(698, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.rest(music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(698, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(698, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.rest(music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(880, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(698, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.rest(music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(659, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(659, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(587, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.rest(music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(494, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(494, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(523, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(587, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(494, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
})
